### ISSUE TITLE
semver breaking change in kornia-image 0.1.10

### ISSUE THREAD

**Issue by astraw** [kornia/kornia-rs#557]
Hi, thanks for the kornia crates!

This program compiles fine with kornia-image 0.1.9:

```
fn main() {
    let data_f32: Vec<f32> = vec![1.0, 2.0, 3.0, 4.0];
    let _image = kornia_image::image::Image::<f32, 3>::new(
        kornia_image::image::ImageSize {
            width: 2,
            height: 2,
        },
        data_f32,
    )
    .unwrap();
}
```

In the recently released 0.1.10, I get this:

```
error[E0107]: struct takes 3 generic arguments but 2 generic arguments were supplied
  --> examples/regrtest/src/main.rs:3:39
   |
 3 |     let _image = kornia_image::image::Image::<f32, 3>::new(
   |                                       ^^^^^   ---  - supplied 2 generic arguments
   |                                       |
   |                                       expected 3 generic arguments
   |
note: struct defined here, with 3 generic parameters: `T`, `C`, `A`
  --> /Users/andrew/Documents/other-peoples-src/kornia-rs/crates/kornia-image/src/image.rs:58:12
   |
58 | pub struct Image<T, const C: usize, A: ImageAllocator>(pub Tensor3<T, A>);
   |            ^^^^^ -  --------------  -
help: add missing generic argument
   |
 3 |     let _image = kornia_image::image::Image::<f32, 3, A>::new(
   |                                                     +++

```

The change was introduced in 8757ebc282623fa3a7fa46b9995b2419a9fe6097.

**Comment by astraw** [comment]
There's also a new argument (`alloc`) required for `Image::new`, `Image::from_size_val`, and other constructors.

**Comment by edgarriba** [comment]
yep! we introduced allocators in the last version to support at some point more backends

**Comment by edgarriba** [comment]
very cool project BTW, happy to receive some feedback about missing features. We are revamping a lot of stuff in relation of calibration and 3d

**Comment by cjpurackal** [comment]
> very cool project BTW, happy to receive some feedback about missing features. We are revamping a lot of stuff in relation of calibration and 3d

Absolutely, happy to help in anyway!
