### ISSUE TITLE
AttributeError: module 'kornia_rs' has no attribute 'read_image_rs'

### ISSUE THREAD

**Issue by safoex** [kornia/kornia-rs#43]
File "/workspace/trusted-plastic/apps/tpcv/tpcv/vision/image_matcher.py", line 42, in __next__
    img1 = K.io.load_image(image_path_1, K.io.ImageLoadType.RGB32)[None, ...]
  File "/usr/local/lib/python3.8/dist-packages/kornia/io/io.py", line 77, in load_image
    image: Tensor = load_image_to_tensor(path_file, device)  # CxHxW
  File "/usr/local/lib/python3.8/dist-packages/kornia/io/io.py", line 38, in load_image_to_tensor
    cv_tensor = kornia_rs.read_image_rs(path_file)
AttributeError: module 'kornia_rs' has no attribute 'read_image_rs'

tested all combinations of kornia 0.7.0 0.7.1 and kornia_rs 0.1.0 0.1.1

**Comment by safoex** [comment]
read_image_rs is definitely mentioned in kornia package, while it's non-existent in kornia_rs (in src, tests, etc)

**Comment by safoex** [comment]
ooof, I managed to find out that kornia 0.7.1 and earlier should work with kornia_rs 0.0.8 
Also from what I see in kornia repo I can deduce that people maintaining kornia realized it's time to add clear dependency on kornia_rs :) So you can close an issue, though it might be useful for others as current last versions of kornia and kornia_rs are not compatible. Hope it gonna be fixed soon!

**Comment by edgarriba** [comment]
this was part of this big refactor: https://github.com/kornia/kornia-rs/pull/32

now the api is more mature and `read_image_rs` is mapped to `read_image_any` which will return directly a numpy array in the python version. This is i hope will stay like for a long while till we are more mature and is all encapsulated into a single `read_image` signature.

you can check here for new usage examples: https://github.com/kornia/kornia-rs/blob/main/py-kornia/tests/test_io.py
